export const allTextureKeys = {
    background: 'background',
    shipBlue: 'shipBlue',
    shipBlue2: 'shipBlue2',
    bomb: 'bomb',
    musicOn: 'musicOn',
    musicOff: 'musicOff',
    effectsOn: 'effectsOn',
    effectsOff: 'effectsOff',
    enemyShip: 'enemyShip',
    man: 'man',
    man2: 'man2',
    woman: 'woman',
    tombStone1: 'tombStone1',
    tombStone2: 'tombStone2',
    spaceShip: 'spaceShip',
    bullet1: 'bullet1',
    bullet2: 'bullet2',
    explosion: 'explosion',
    explosion1: 'explosion1',
    explosion2: 'explosion2',
    explosion3: 'explosion3',
}

const appTextures = {
    [allTextureKeys.background] : './src/sprites/bg_1920x180px.jpg',
    [allTextureKeys.shipBlue] : './src/sprites/shipBlue.png',
    [allTextureKeys.shipBlue2] : './src/sprites/shipBlue2.png',
    [allTextureKeys.bomb] : './src/sprites/bomb.png',
    [allTextureKeys.musicOn] : './src/sprites/music_on.png',
    [allTextureKeys.musicOff] : './src/sprites/music_off.png',
    [allTextureKeys.effectsOn] : './src/sprites/volume_on.png',
    [allTextureKeys.effectsOff] : './src/sprites/volume_off.png',
    [allTextureKeys.enemyShip] : './src/sprites/shipBlue.png',
    [allTextureKeys.man] : './src/sprites/man.png',
    [allTextureKeys.man2] : './src/sprites/man2.png',
    [allTextureKeys.woman] : './src/sprites/woman.png',
    [allTextureKeys.tombStone1] : './src/sprites/TombStone1.png',
    [allTextureKeys.tombStone2] : './src/sprites/TombStone2.png',
    [allTextureKeys.spaceShip] : './src/sprites/player.png',
    [allTextureKeys.bullet1] : './src/sprites/bullet1.json',
    [allTextureKeys.bullet2] : './src/sprites/bullet2.json',
    [allTextureKeys.explosion] : './src/sprites/explosion.json',
    [allTextureKeys.explosion1] : './src/sprites/explosion1.json',
    [allTextureKeys.explosion2] : './src/sprites/explosion2.json',
    [allTextureKeys.explosion3] : './src/sprites/explosion3.json',
}

export default appTextures